### ISSUE TITLE
[Testcafe-cucumber] steps with multiple examples runs only once

### ISSUE THREAD

**Issue by natkrish** [rquellh/testcafe-cucumber#21]
"dependencies": {
    "base64-img": "^1.0.4",
    "cucumber": "^4.2.1",
    "eslint": "^4.19.1",
    "npm": "^6.0.0",
    "testcafe": "^0.23.2"
  },
I have been trying to run a scenario which looks something like this 
@gpnotification
Feature: As a patient, I want to select my preferred GP Surgery
    so that I can keep my GP informed of LOD online consultation

    Background: A patient already added a product to basket and is on delivery page
        Given I am on delivery page on desktop

    @verifyGPNotification
    Scenario Outline: Verify that a patient can see GP notification on delivery page when Feature flag is ON
        And I choose my "<deliveryoptions>"
        When I access the page with feature flag ON
        Then I verify that I can see GP notification

        Examples:
            | deliveryoptions  |
            | nextdaydelivery  |
            | clickncollect    |
            | standarddelivery |
When I run - npm test - testcafe runs only for the first row in the example table. It doesnt iterate. I get the following output in console but there is nothing more to debug 
> testcafe-cucumber@0.1.0 test C:\Users\krish.murthy\intellijworkspace\archive\testcafe-cucumber
> cucumber-js.cmd

 Running tests in:
 - Chrome 69.0.3497 / Windows 10.0.0

 fixture
....... √ test

 1 passed (40s)
npm ERR! Test failed.  See above for more details.

**Comment by natkrish** [comment]
Additional output
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'test' ]
2 info using npm@5.6.0
3 info using node@v9.5.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle testcafe-cucumber@0.1.0~pretest: testcafe-cucumber@0.1.0
6 info lifecycle testcafe-cucumber@0.1.0~test: testcafe-cucumber@0.1.0
7 verbose lifecycle testcafe-cucumber@0.1.0~test: unsafe-perm in lifecycle true
8 verbose lifecycle testcafe-cucumber@0.1.0~test: PATH: C:\Users\krish.murthy\AppData\Roaming\nvm\v9.5.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\krish.murthy\intellijworkspace\archive\testcafe-cucumber\node_modules\.bin;%PYTHON%;C:\Users\krish.murthy\.windows-build-tools\python27;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Users\krish.murthy\node_modules\.bin;C:\Users\krish.murthy\Desktop\allure-2.6.0\allure-2.6.0\bin;C:\Users\krish.murthy\AppData\Local\Android\Sdk\tools;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Maven\apache-maven-3.5.2\bin;C:\Program Files\PuTTY\;C:\Program Files\Java\jdk1.8.0_152;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Yarn\bin;C:\Program Files\dotnet\;C:\Program Files\Gauge\bin;C:\Program Files (x86)\NUnit.org\nunit-console;C:\ProgramData\chocolatey\bin;C:\Users\krish.murthy\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Users\krish.murthy\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\Microsoft VS Code\bin;C:\WINDOWS\System32\OpenSSH\;C:\Users\krish.murthy\.windows-build-tools\python27;C:\Users\krish.murthy\.windows-build-tools\python27\;C:\Users\krish.murthy\AppData\Roaming\nvm\v9.5.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Program Files\nodejs\node_modules\windows-build-tools\node_modules\.bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Users\krish.murthy\node_modules\.bin;C:\Users\krish.murthy\Desktop\allure-2.6.0\allure-2.6.0\bin;C:\Users\krish.murthy\AppData\Local\Android\Sdk\tools;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Maven\apache-maven-3.5.2\bin;C:\Program Files\PuTTY\;C:\Program Files\Java\jdk1.8.0_152;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Yarn\bin;C:\Program Files\dotnet\;C:\Program Files\Gauge\bin
9 verbose lifecycle testcafe-cucumber@0.1.0~test: CWD: C:\Users\krish.murthy\intellijworkspace\archive\testcafe-cucumber
10 silly lifecycle testcafe-cucumber@0.1.0~test: Args: [ '/d /s /c', 'cucumber-js.cmd' ]
11 silly lifecycle testcafe-cucumber@0.1.0~test: Returned: code: 1  signal: null
12 info lifecycle testcafe-cucumber@0.1.0~test: Failed to exec test script
13 verbose stack Error: testcafe-cucumber@0.1.0 test: `cucumber-js.cmd`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\krish.murthy\AppData\Roaming\nvm\v9.5.0\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:160:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\krish.murthy\AppData\Roaming\nvm\v9.5.0\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:160:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid testcafe-cucumber@0.1.0
15 verbose cwd C:\Users\krish.murthy\intellijworkspace\archive\testcafe-cucumber
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
18 verbose node v9.5.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error testcafe-cucumber@0.1.0 test: `cucumber-js.cmd`
22 error Exit status 1
23 error Failed at the testcafe-cucumber@0.1.0 test script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by natkrish** [comment]
Sorry it was my mistake. I upgraded cucumber and testcafe to the latest in package.json and that caused all this issue. I put them back in to what was suggested in this repo and it works perfectly fine. @rquellh do you have any plans on upgrading them?
